---
sidebar: sidebar 
permalink: scpivs44_restore_the_most_recent_backup_of_the_mysql_database.html 
keywords:  
summary: 'Vous pouvez utiliser la console de maintenance pour restaurer la sauvegarde la plus récente de la base de données MySQL (également appelée base de données NSM) pour le SnapCenter Plug-in for VMware vSphere.' 
---
= Restaurer la sauvegarde la plus récente de la base de données MySQL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser la console de maintenance pour restaurer la sauvegarde la plus récente de la base de données MySQL (également appelée base de données NSM) pour le SnapCenter Plug-in for VMware vSphere.

.Étapes
. Ouvrez une fenêtre de console de maintenance.
+
link:scpivs44_access_the_maintenance_console.html["Accéder à la console de maintenance"^] .

. Depuis le menu principal, entrez l'option *1) Configuration de l'application*.
. Dans le menu de configuration de l'application, entrez l'option *6) Sauvegarde et restauration MySQL*.
. Dans le menu de configuration de sauvegarde et de restauration MySQL, entrez l'option *4) Restaurer la sauvegarde MySQL*.
. À l’invite « Restaurer à l’aide de la sauvegarde la plus récente », saisissez *y*, puis appuyez sur *Entrée*.
+
La base de données MySQL de sauvegarde est restaurée à son emplacement d'origine.


