---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vms.html 
keywords:  
summary: 'Pour effectuer des opérations de restauration pour les sauvegardes de machines virtuelles à l"aide du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite d"appels d"API REST.' 
---
= Workflow de l'API REST pour restaurer les machines virtuelles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour effectuer des opérations de restauration pour les sauvegardes de machines virtuelles à l'aide du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite d'appels d'API REST.

Pour chaque API REST, ajoutez `\https://<server>:<port>` à l'avant de l'API REST pour former un point de terminaison complet.

|===
| Étape | API REST | Commentaires 


| 1 | Aller à `\http://<vCenter-IP>/mob` | Recherchez la machine virtuelle moref à partir de l’URL des objets gérés VMware.  Notez le *moref* pour la VM que vous souhaitez restaurer. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`obtient une liste de sauvegardes pour la VM spécifiée.  Passez le *moref* de l’étape 1.  Notez le *backupId* de la sauvegarde que vous souhaitez restaurer. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`obtient l'emplacement de l'instantané pour la sauvegarde spécifiée.  Transmettez le *backupId* de l’étape 2.  Notez les informations *snapshotLocationsList*. 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`obtient les informations sur l'hôte sur lequel la sauvegarde est stockée.  Notez les informations *availableEsxHostsList*. 


| 5 | `/4.1/vm/{moref}/backups/
{backupId}/restore`  a| 
`Restore a VM from a backup`restaure la sauvegarde spécifiée.  Transmettez les informations des étapes 3 et 4 dans l'attribut *restoreLocations*.


NOTE: Si la sauvegarde de la machine virtuelle est une sauvegarde partielle, définissez le `restartVM` paramètre à « false ».


NOTE: Vous ne pouvez pas restaurer une machine virtuelle qui est un modèle.

|===