---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: 'Après la mise à niveau du SnapCenter Plug-in for VMware vSphere vers un nouveau correctif de la même version, les tâches récentes ou d"autres informations peuvent ne pas s"afficher dans le tableau de bord et le moniteur de tâches.' 
---
= Informations non affichées après la mise à niveau vers un nouveau correctif de la même version
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après la mise à niveau du SnapCenter Plug-in for VMware vSphere vers un nouveau correctif de la même version, les tâches récentes ou d'autres informations peuvent ne pas s'afficher dans le tableau de bord et le moniteur de tâches.

Si vous effectuez une mise à niveau vers un nouveau correctif de la même version, vous devez effacer le cache du SnapCenter Plug-in for VMware vSphere sur le serveur Web vCenter et redémarrer le serveur avant la mise à niveau ou l'enregistrement.

Si le cache du plug-in n'est pas vidé, les tâches récentes ne s'affichent pas dans le tableau de bord et le moniteur de tâches dans les scénarios suivants :

* Le SnapCenter Plug-in for VMware vSphere a été déployé à l’aide de vCenter, puis mis à niveau ultérieurement vers un correctif dans la même version.
* L'appliance virtuelle SnapCenter VMware a été déployée dans vCenter 1.  Plus tard, ce SnapCenter Plug-in for VMware vSphere a été enregistré sur un nouveau vCenter2.  Une nouvelle instance du SnapCenter Plug-in for VMware vSphere est créée avec un correctif et enregistrée sur vCenter1.  Cependant, étant donné que vCenter1 dispose toujours du plug-in mis en cache du premier SnapCenter Plug-in for VMware vSphere sans le correctif, le cache doit être vidé.


Le cache se trouve aux emplacements suivants, en fonction du type de système d'exploitation du serveur :

* Appareil Linux vCenter Server
+
`/etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity/`

* Système d'exploitation Windows
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== Solution de contournement si vous avez déjà effectué la mise à niveau avant de vider le cache

. Connectez-vous à l'interface graphique de gestion du SnapCenter Plug-in for VMware vSphere .
+
L'adresse IP s'affiche lorsque vous déployez le SnapCenter Plug-in for VMware vSphere.

. Sélectionnez *Configuration* dans le volet de navigation de gauche, puis sélectionnez l'option Service dans la section *Détails du plug-in* pour désactiver le plug-in.
+
Le service SnapCenter Plug-in for VMware vSphere est désactivé et l’extension n’est pas enregistrée dans vCenter.

. Localisez le `vsphere-client-serenity` dossier, puis recherchez le `com.netapp.scv.client-<release-number>` dossier et supprimez-le.
+
Le nom du dossier change à chaque version.

. Redémarrez le serveur vCenter.
. Connectez-vous au client VMware vSphere.
. Sélectionnez *Configuration* dans le volet de navigation de gauche, puis sélectionnez l’option Service dans la section *Détails du plug-in* pour activer le plug-in.
+
Le service SnapCenter Plug-in for VMware vSphere est activé et l’extension est enregistrée dans vCenter.


