---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 'Vous pouvez restaurer des VMDK existants, ou des VMDK supprimés ou détachés, à partir d"une sauvegarde principale ou secondaire de machines virtuelles traditionnelles ou de machines virtuelles vVol.' 
---
= Restaurer les VMDK à partir des sauvegardes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer des VMDK existants, ou des VMDK supprimés ou détachés, à partir d'une sauvegarde principale ou secondaire de machines virtuelles traditionnelles ou de machines virtuelles vVol.

Vous pouvez restaurer un ou plusieurs disques de machine virtuelle (VMDK) sur une machine virtuelle vers le même magasin de données.


TIP: Pour améliorer les performances des opérations de restauration dans les environnements NFS, activez l'API vStorage de l'application VMware pour l'intégration de baies (VAAI).

.Avant de commencer
* Une sauvegarde doit exister.
+
Vous devez avoir créé une sauvegarde de la machine virtuelle à l’aide du SnapCenter Plug-in for VMware vSphere.

* La VM ne doit pas être en transit.
+
La machine virtuelle que vous souhaitez restaurer ne doit pas être dans un état vMotion ou Storage vMotion.



.À propos de cette tâche
* Si le VMDK est supprimé ou détaché de la VM, l’opération de restauration attache le VMDK à la VM.
* Une opération de restauration peut échouer si le niveau de stockage du FabricPool où se trouve la machine virtuelle n'est pas disponible.
* Les opérations de connexion et de restauration connectent les VMDK à l'aide du contrôleur SCSi par défaut.  Cependant, lorsque les VMDK attachés à une machine virtuelle avec un disque NVMe sont sauvegardés, les opérations d'attachement et de restauration utilisent le contrôleur NVMe s'il est disponible.


.Étapes
. Dans l’interface graphique du client VMware vSphere, sélectionnez *Menu* dans la barre d’outils, puis sélectionnez *VM et modèles* dans la liste déroulante.
. Dans le volet de navigation de gauche, cliquez avec le bouton droit sur une machine virtuelle, puis sélectionnez * SnapCenter Plug-in for VMware vSphere* dans la liste déroulante, puis sélectionnez * Restaurer * dans la liste déroulante secondaire.
. Dans l’assistant *Restauration*, sur la page Sélectionner une sauvegarde, sélectionnez la copie de sauvegarde à partir de laquelle vous souhaitez effectuer la restauration.
+
Vous pouvez rechercher un nom de sauvegarde spécifique ou un nom de sauvegarde partielle, ou vous pouvez filtrer la liste de sauvegarde en sélectionnant l'icône de filtre et en sélectionnant une plage de dates et d'heures, en sélectionnant si vous souhaitez des sauvegardes contenant des snapshots VMware, si vous souhaitez des sauvegardes montées et un emplacement principal ou secondaire.  Sélectionnez *OK* pour revenir à l’assistant.

. Sur la page *Sélectionner l’étendue*, sélectionnez la destination de la restauration.
+
|===
| Pour restaurer… | Spécifiez la destination de la restauration… 


| Le magasin de données d'origine | Sélectionnez *Disque particulier* dans la liste déroulante, puis sélectionnez *Suivant*.  Dans le tableau de sélection du magasin de données, vous pouvez sélectionner ou désélectionner n’importe quel VMDK. 


| Un magasin de données alternatif dans un autre emplacement | Sélectionnez le magasin de données de destination et sélectionnez un autre magasin de données dans la liste. 
|===
. Sur la page *Sélectionner l’emplacement*, sélectionnez l’instantané que vous souhaitez restaurer (principal ou secondaire).
. Consultez la page Résumé, puis sélectionnez *Terminer*.
. Facultatif : Surveillez la progression de l'opération en sélectionnant *Tâches récentes* en bas de l'écran.
. Actualisez l'écran pour afficher les informations mises à jour.

