---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: Pour utiliser les fonctionnalités de SnapCenter afin de protéger les machines virtuelles, les banques de données et les bases de données cohérentes avec les applications sur les machines virtualisées, vous devez déployer SnapCenter Plug-in for VMware vSphere. 
---
= Déployer le SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour utiliser les fonctionnalités de SnapCenter afin de protéger les machines virtuelles, les banques de données et les bases de données cohérentes avec les applications sur les machines virtualisées, vous devez déployer SnapCenter Plug-in for VMware vSphere.

.Avant de commencer
Cette section répertorie toutes les actions nécessaires à effectuer avant de commencer le déploiement.


NOTE: Le déploiement OVA est pris en charge dans VMware vCenter 7u1 et versions ultérieures.

* Vous devez avoir lu les exigences de déploiement.
* Vous devez exécuter une version prise en charge de vCenter Server.
* Vous devez avoir configuré et installé votre environnement vCenter Server.
* Vous devez avoir configuré un hôte ESXi pour le SnapCenter Plug-in for VMware vSphere VM.
* Vous devez avoir téléchargé le fichier .tar du SnapCenter Plug-in for VMware vSphere .
* Vous devez disposer des informations d’authentification de connexion pour votre instance vCenter Server.
* Vous devez disposer d'un certificat avec des fichiers de clés publiques et privées valides.  Pour plus d'informations, reportez-vous aux articles sous https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["Gestion des certificats de stockage"] section.
* Vous devez vous être déconnecté et avoir fermé toutes les sessions de navigateur du client vSphere et supprimé le cache du navigateur pour éviter tout problème de cache du navigateur lors du déploiement du SnapCenter Plug-in for VMware vSphere.
* Vous devez avoir activé Transport Layer Security (TLS) dans vCenter.  Reportez-vous à la documentation VMware.
* Si vous prévoyez d'effectuer des sauvegardes dans des vCenter autres que celui dans lequel le SnapCenter Plug-in for VMware vSphere est déployé, le serveur ESXi, le SnapCenter Plug-in for VMware vSphere et chaque vCenter doivent être synchronisés à la même heure.
* Pour protéger les machines virtuelles sur les banques de données vVol, vous devez d’abord déployer les ONTAP tools for VMware vSphere.  Pour obtenir les dernières informations sur les versions prises en charge des outils ONTAP , reportez-vous à https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp"^] .  Les outils ONTAP provisionnent et configurent le stockage sur ONTAP et sur le client Web VMware.


Déployez le SnapCenter Plug-in for VMware vSphere dans le même fuseau horaire que vCenter.  Les planifications de sauvegarde sont exécutées dans le fuseau horaire dans lequel le SnapCenter Plug-in for VMware vSphere est déployé. vCenter signale les données dans le fuseau horaire dans lequel se trouve vCenter.  Par conséquent, si le SnapCenter Plug-in for VMware vSphere et vCenter se trouvent dans des fuseaux horaires différents, les données du tableau de bord du SnapCenter Plug-in for VMware vSphere peuvent ne pas être identiques à celles des rapports.

.Étapes
. Pour VMware vCenter 7.0.3 et les versions ultérieures, suivez les étapes décrites danslink:scpivs44_download_the_ova_open_virtual_appliance.html["Téléchargez l'appliance virtuelle ouverte (OVA)"^] pour importer les certificats dans vCenter.
. Dans votre navigateur, accédez à VMware vSphere vCenter.
+

NOTE: Pour les clients Web HTML avec adresse IPv6, vous devez utiliser Chrome ou Firefox.

. Connectez-vous à la page *VMware vCenter Single Sign-On*.
. Dans le volet du navigateur, cliquez avec le bouton droit sur n'importe quel objet d'inventaire qui est un objet parent valide d'une machine virtuelle, tel qu'un centre de données, un cluster ou un hôte, et sélectionnez *Déployer le modèle OVF* pour démarrer l'assistant de déploiement VMware.
. Extrayez le fichier .tar, qui contient le fichier .ova sur votre système local.  Sur la page *Sélectionner un modèle OVF*, spécifiez l'emplacement du `.ova` fichier à l'intérieur du dossier .tar extrait.
. Sélectionnez *Suivant*.
. Sur la page *Sélectionner un nom et un dossier*, saisissez un nom unique pour la machine virtuelle ou la vApp, sélectionnez un emplacement de déploiement, puis sélectionnez *Suivant*.
+
Cette étape spécifie où importer le `.tar` fichier dans vCenter.  Le nom par défaut de la machine virtuelle est le même que le nom de la machine virtuelle sélectionnée. `.ova` déposer.  Si vous modifiez le nom par défaut, choisissez un nom unique dans chaque dossier de machine virtuelle vCenter Server.

+
L’emplacement de déploiement par défaut de la machine virtuelle est l’objet d’inventaire où vous avez démarré l’assistant.

. Sur la page *Sélectionner une ressource*, sélectionnez la ressource sur laquelle vous souhaitez exécuter le modèle de machine virtuelle déployé, puis sélectionnez *Suivant*.
. Sur la page *Détails de l'avis*, vérifiez le `.tar` détails du modèle et sélectionnez *Suivant*.
. Sur la page *Accords de licence*, cochez la case *J'accepte tous les accords de licence*.
. Sur la page *Sélectionner le stockage*, définissez où et comment stocker les fichiers du modèle OVF déployé.
+
.. Sélectionnez le format de disque pour les VMDK.
.. Sélectionnez une politique de stockage de machine virtuelle.
+
Cette option est disponible uniquement si les politiques de stockage sont activées sur la ressource de destination.

.. Sélectionnez un magasin de données pour stocker le modèle OVA déployé.
+
Le fichier de configuration et les fichiers de disque virtuel sont stockés sur le magasin de données.

+
Sélectionnez une banque de données suffisamment grande pour accueillir la machine virtuelle ou la vApp et tous les fichiers de disque virtuel associés.



. Sur la page *Sélectionner les réseaux*, procédez comme suit :
+
.. Sélectionnez un réseau source et mappez-le à un réseau de destination,
+
La colonne Réseau source répertorie tous les réseaux définis dans le modèle OVA.

.. Dans la section *Paramètres d'allocation IP*, sélectionnez le protocole d'adresse IP requis, puis sélectionnez *Suivant*.
+
Le SnapCenter Plug-in for VMware vSphere prend en charge une interface réseau.  Si vous avez besoin de plusieurs adaptateurs réseau, vous devez les configurer manuellement. Se référer à https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["Article de la base de connaissances : Comment créer des adaptateurs réseau supplémentaires"^] .



. Sur la page *Personnaliser le modèle*, procédez comme suit :
+
.. Dans la section *S'inscrire sur un vCenter existant*, saisissez le nom du vCenter et les informations d'identification du vCenter de l'appliance virtuelle.
+
Dans le champ *nom d'utilisateur vCenter*, saisissez le nom d'utilisateur au format `domain\username` .

.. Dans la section *Créer des informations d'identification SCV*, saisissez les informations d'identification locales.
+
Dans le champ *Nom d'utilisateur*, saisissez le nom d'utilisateur local ; n'incluez pas les détails du domaine.

+

IMPORTANT: Notez le nom d’utilisateur et le mot de passe que vous spécifiez.  Vous devez utiliser ces informations d’identification si vous souhaitez modifier ultérieurement la configuration du SnapCenter Plug-in for VMware vSphere .

.. Saisissez les informations d’identification de l’utilisateur principal.
.. Dans la section *Configurer les propriétés du réseau*, entrez le nom de l’hôte.
+
... Dans la section *Configurer les propriétés du réseau IPv4*, saisissez les informations réseau telles que l'adresse IPv4, le masque de réseau IPv4, la passerelle IPv4, le DNS principal IPv4, le DNS secondaire IPv4 et les domaines de recherche IPv4.
... Dans la section *Configurer les propriétés du réseau IPv6*, saisissez les informations réseau telles que l'adresse IPv6, le masque de réseau IPv6, la passerelle IPv6, le DNS principal IPv6, le DNS secondaire IPv6 et les domaines de recherche IPv6.
+
Sélectionnez les champs d’adresse IPv4 ou IPv6, ou les deux, si approprié.  Si vous utilisez à la fois des adresses IPv4 et IPv6, vous devez spécifier le DNS principal pour l'une d'entre elles uniquement.

+

IMPORTANT: Vous pouvez ignorer ces étapes et laisser les entrées vides dans la section *Configurer les propriétés du réseau*, si vous souhaitez continuer avec DHCP comme configuration réseau.



.. Dans *Configurer la date et l’heure*, sélectionnez le fuseau horaire dans lequel se trouve le vCenter.


. Sur la page *Prêt à terminer*, vérifiez la page et sélectionnez *Terminer*.
+
Tous les hôtes doivent être configurés avec des adresses IP (les noms d'hôtes FQDN ne sont pas pris en charge).  L'opération de déploiement ne valide pas votre entrée avant le déploiement.

+
Vous pouvez afficher la progression du déploiement à partir de la fenêtre Tâches récentes pendant que vous attendez la fin des tâches d'importation et de déploiement OVF.

+
Lorsque le SnapCenter Plug-in for VMware vSphere est déployé avec succès, il est déployé en tant que machine virtuelle Linux, enregistré auprès de vCenter et un client VMware vSphere est installé.

. Accédez à la machine virtuelle sur laquelle le SnapCenter Plug-in for VMware vSphere a été déployé, puis sélectionnez l’onglet *Résumé*, puis cochez la case *Mettre sous tension* pour démarrer l’appliance virtuelle.
. Pendant que le SnapCenter Plug-in for VMware vSphere est sous tension, cliquez avec le bouton droit sur le SnapCenter Plug-in for VMware vSphere, sélectionnez *SE invité*, puis sélectionnez *Installer les outils VMware*.
+
Les outils VMware sont installés sur la machine virtuelle sur laquelle le SnapCenter Plug-in for VMware vSphere est déployé.  Pour plus d’informations sur l’installation des outils VMware, consultez la documentation VMware.

+
Le déploiement peut prendre quelques minutes.  Le déploiement réussi est indiqué lorsque le SnapCenter Plug-in for VMware vSphere est sous tension, que les outils VMware sont installés et que l'écran vous invite à vous connecter au SnapCenter Plug-in for VMware vSphere.  Vous pouvez changer votre configuration réseau de DHCP à statique lors du premier redémarrage.  Cependant, le passage du mode statique au mode DHCP n'est pas pris en charge.

+
L'écran affiche l'adresse IP où le SnapCenter Plug-in for VMware vSphere est déployé. Notez l'adresse IP. Vous devez vous connecter à l'interface graphique de gestion du SnapCenter Plug-in for VMware vSphere si vous souhaitez apporter des modifications à la configuration du SnapCenter Plug-in for VMware vSphere .

. Connectez-vous à l'interface graphique de gestion du SnapCenter Plug-in for VMware vSphere à l'aide de l'adresse IP affichée sur l'écran de déploiement et des informations d'identification que vous avez fournies dans l'assistant de déploiement, puis vérifiez sur le tableau de bord que le SnapCenter Plug-in for VMware vSphere est correctement connecté à vCenter et est activé.
+
Utiliser le format `\https://<appliance-IP-address>:8080` pour accéder à l'interface graphique de gestion.

+
Connectez-vous avec le nom d’utilisateur et le mot de passe administrateur définis au moment du déploiement et le jeton MFA généré à l’aide de la console de maintenance.

+
Si le SnapCenter Plug-in for VMware vSphere n'est pas activé, reportez-vous àlink:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Redémarrez le service client VMware vSphere"] .

+
Si le nom d'hôte est « UnifiedVSC/SCV », redémarrez l'appliance.  Si le redémarrage de l'appliance ne modifie pas le nom d'hôte en celui spécifié, vous devez réinstaller l'appliance.



.Après avoir terminé
Vous devez compléter les informations requiseslink:scpivs44_post_deployment_required_operations_and_issues.html["opérations post-déploiement"] .
