---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: 'Pour modifier les planifications intégrées des tâches client VMware vSphere à l"aide du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite des appels d"API REST.' 
---
= Flux de travail de l'API REST pour modifier les planifications intégrées
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour modifier les planifications intégrées des tâches client VMware vSphere à l'aide du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite des appels d'API REST.

Les planifications intégrées sont les planifications fournies dans le cadre du produit ; par exemple, la planification de vidage de la base de données MySQL.  Vous pouvez modifier les horaires suivants :
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Pour chaque API REST, ajoutez `\https://<server>:<port>` à l'avant de l'API REST pour former un point de terminaison complet.

|===
| Étape | API REST | Commentaires 


| 1 | `/4.1/schedules` | `Get all built-in`scheduler obtient une liste des plannings de tâches initialement fournis dans le produit.  Notez le nom du planning que vous souhaitez modifier et l’expression cron associée. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule`modifie le calendrier nommé.  Transmettez le nom de la planification de l’étape 1 et créez une nouvelle expression cron pour la planification. 
|===