---
sidebar: sidebar 
permalink: scpivs44_rest_apis__download_jobs_and_generate_reports.html 
keywords:  
summary: 'Pour générer des rapports et télécharger des journaux pour les tâches client VMware vSphere à l"aide du SnapCenter Plug-in for VMware vSphere , vous devez utiliser les appels d"API REST pour VMware vSphere.' 
---
= API REST pour télécharger des tâches et générer des rapports
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour générer des rapports et télécharger des journaux pour les tâches client VMware vSphere à l'aide du SnapCenter Plug-in for VMware vSphere , vous devez utiliser les appels d'API REST pour VMware vSphere.

Pour chaque API REST, ajoutez `\https://<server>:<port>` à l'avant de l'API REST pour former un point de terminaison complet.



== Utilisez les API REST suivantes dans la section Emplois pour obtenir des informations détaillées sur les emplois :

|===
| API REST | Commentaires 


| `/4.1/jobs` | `Get all jobs`obtient les détails du travail pour plusieurs travaux.  Vous pouvez restreindre la portée de la demande en spécifiant un type de travail, tel que `backup` , `mountBackup` , ou `restore` . 


| `/4.1/jobs/{id}` | `Get job details`obtient des informations détaillées pour le travail spécifié. 
|===


== Utilisez l’API REST suivante dans la section Tâches pour télécharger les journaux des tâches :

|===
| API REST | Commentaires 


| `/4.1/jobs/{id}/logs` | `getJobLogsById`télécharge les journaux pour le travail spécifié. 
|===


== Utilisez les API REST suivantes dans la section Rapports pour générer des rapports :

|===
| API REST | Commentaires 


| `4.1/reports/protectedVM` | `Get Protected VM List`obtient une liste des machines virtuelles protégées au cours des sept derniers jours. 


| `/4.1/reports/
unProtectedVM` | `Get Unprotected VM List`obtient une liste des machines virtuelles non protégées au cours des sept derniers jours. 
|===