---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: 'Vous pouvez restaurer des fichiers ou des dossiers à partir d’un disque de machine virtuelle (VMDK) sur un système d’exploitation invité Windows.' 
---
= Flux de travail, prérequis et limitations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez restaurer des fichiers ou des dossiers à partir d’un disque de machine virtuelle (VMDK) sur un système d’exploitation invité Windows.



== Flux de travail de restauration des invités

Les opérations de restauration du système d’exploitation invité incluent les étapes suivantes :

. Attacher
+
Attachez un disque virtuel à une machine virtuelle invitée ou à une machine virtuelle proxy et démarrez une session de restauration de fichiers invités.

. Attendez
+
Attendez que l’opération de connexion soit terminée avant de pouvoir parcourir et restaurer.  Lorsque l'attache

+
l'opération se termine, une session de restauration de fichiers invités est automatiquement créée et une notification par courrier électronique est

+
envoyé.

. Sélectionner des fichiers ou des dossiers
+
Parcourez le VMDK dans la session de restauration de fichiers invités et sélectionnez un ou plusieurs fichiers ou dossiers à restaurer.

. Restaurer
+
Restaurer les fichiers ou dossiers sélectionnés à un emplacement spécifié.





== Conditions préalables à la restauration des fichiers et dossiers invités

Avant de restaurer un ou plusieurs fichiers ou dossiers à partir d’un VMDK sur un système d’exploitation invité Windows, vous devez connaître toutes les exigences.

* Les outils VMware doivent être installés et en cours d’exécution.
+
SnapCenter utilise les informations des outils VMware pour établir une connexion au système d'exploitation invité VMware.

* Le système d’exploitation invité Windows doit exécuter Windows Server 2008 R2 ou une version ultérieure.
+
Pour obtenir les dernières informations sur les versions prises en charge, reportez-vous à https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp (IMT)"^] .

* Les informations d’identification de la machine virtuelle cible doivent spécifier le compte d’administrateur de domaine intégré ou le compte d’administrateur local intégré.  Le nom d'utilisateur doit être « Administrateur ».  Avant de démarrer l’opération de restauration, les informations d’identification doivent être configurées pour la machine virtuelle à laquelle vous souhaitez attacher le disque virtuel.  Les informations d’identification sont requises à la fois pour l’opération de connexion et pour l’opération de restauration ultérieure.  Les utilisateurs du groupe de travail peuvent utiliser le compte administrateur local intégré.
+

IMPORTANT: Si vous devez utiliser un compte qui n’est pas le compte administrateur intégré, mais qui dispose de privilèges administratifs au sein de la machine virtuelle, vous devez désactiver l’UAC sur la machine virtuelle invitée.

* Vous devez connaître l'instantané de sauvegarde et le VMDK à partir desquels effectuer la restauration.
+
Le SnapCenter Plug-in for VMware vSphere ne prend pas en charge la recherche de fichiers ou de dossiers à restaurer.  Par conséquent, avant de commencer, vous devez connaître l’emplacement des fichiers ou des dossiers par rapport à l’instantané et au VMDK correspondant.

* Le disque virtuel à connecter doit se trouver dans une sauvegarde SnapCenter .
+
Le disque virtuel qui contient le fichier ou le dossier que vous souhaitez restaurer doit se trouver dans une sauvegarde de machine virtuelle effectuée à l'aide du dispositif virtuel pour SnapCenter Plug-in for VMware vSphere.

* Pour utiliser une machine virtuelle proxy, la machine virtuelle proxy doit être configurée.
+
Si vous souhaitez attacher un disque virtuel à une machine virtuelle proxy, la machine virtuelle proxy doit être configurée avant le début de l'opération d'attachement et de restauration.

* Pour les fichiers dont les noms ne sont pas en alphabet anglais, vous devez les restaurer dans un répertoire et non sous forme de fichier unique.
+
Vous pouvez restaurer des fichiers avec des noms non alphabétiques, tels que des kanji japonais, en restaurant le répertoire dans lequel se trouvent les fichiers.

* La restauration à partir d'un système d'exploitation invité Linux n'est pas prise en charge
+
Vous ne pouvez pas restaurer des fichiers et des dossiers à partir d’une machine virtuelle exécutant un système d’exploitation invité Linux.  Cependant, vous pouvez attacher un VMDK, puis restaurer manuellement les fichiers et les dossiers.  Pour obtenir les dernières informations sur les systèmes d'exploitation invités pris en charge, reportez-vous à https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp (IMT)"^] .





== Limitations de la restauration des fichiers invités

Avant de restaurer un fichier ou un dossier à partir d’un système d’exploitation invité, vous devez savoir ce que la fonctionnalité ne prend pas en charge.

* Vous ne pouvez pas restaurer les types de disques dynamiques dans un système d’exploitation invité.
* Si vous restaurez un fichier ou un dossier chiffré, l’attribut de chiffrement n’est pas conservé.  Vous ne pouvez pas restaurer des fichiers ou des dossiers dans un dossier crypté.
* La page Parcourir les fichiers invités affiche les fichiers et dossiers cachés, que vous ne pouvez pas filtrer.
* Vous ne pouvez pas restaurer à partir d’un système d’exploitation invité Linux.
+
Vous ne pouvez pas restaurer des fichiers et des dossiers à partir d’une machine virtuelle exécutant un système d’exploitation invité Linux.  Cependant, vous pouvez attacher un VMDK, puis restaurer manuellement les fichiers et les dossiers.  Pour obtenir les dernières informations sur les systèmes d'exploitation invités pris en charge, reportez-vous à la https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp (IMT)"^] .

* Vous ne pouvez pas restaurer d’un système de fichiers NTFS vers un système de fichiers FAT.
+
Lorsque vous essayez de restaurer du format NTFS au format FAT, le descripteur de sécurité NTFS n'est pas copié car le système de fichiers FAT ne prend pas en charge les attributs de sécurité Windows.

* Vous ne pouvez pas restaurer les fichiers invités à partir d’un VMDK cloné ou d’un VMDK non initialisé.
* Vous ne pouvez pas restaurer la structure du répertoire d’un fichier.
+
Si un fichier dans un répertoire imbriqué est sélectionné pour être restauré, le fichier n'est pas restauré avec la même structure de répertoire.  L'arborescence des répertoires n'est pas restaurée, seulement le fichier.  Si vous souhaitez restaurer une arborescence de répertoires, vous pouvez copier le répertoire lui-même en haut de la structure.

* Vous ne pouvez pas restaurer les fichiers invités d’une machine virtuelle vVol vers un autre hôte.
* Vous ne pouvez pas restaurer les fichiers invités cryptés.

