---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__add_and_modify_storage_vms.html 
keywords:  
summary: 'Pour effectuer des opérations d"ajout et de modification de machine virtuelle de stockage à l"aide des API REST du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite d"appels d"API REST.' 
---
= Workflows d'API REST pour ajouter et modifier des machines virtuelles de stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour effectuer des opérations d'ajout et de modification de machine virtuelle de stockage à l'aide des API REST du SnapCenter Plug-in for VMware vSphere , vous devez suivre la séquence prescrite d'appels d'API REST.

Pour chaque API REST, ajoutez `\https://<server>:<port>` à l'avant de l'API REST pour former un point de terminaison complet.

Pour ajouter des opérations de VM de stockage, suivez ce workflow :

|===
| Étape | API REST | Commentaires 


| 1 | `/4.1/storage-system` | `Add Storage System`ajoute la machine virtuelle de stockage spécifiée au SnapCenter Plug-in for VMware vSphere. 
|===
Pour modifier les opérations de la machine virtuelle de stockage, suivez ce flux de travail :

|===
| Étape | API REST | Commentaires 


| 1 | `/4.1/storage-system` | `getSvmAll`obtient la liste de toutes les machines virtuelles de stockage disponibles.  Notez le *nom* de la machine virtuelle de stockage que vous souhaitez modifier. 


| 2 | `/4.1/storage-system` | `Modify Storage System`modifie la machine virtuelle de stockage spécifiée.  Transmettez le *nom* de l’étape 1 en plus de tous les autres attributs requis. 
|===