---
sidebar: sidebar 
permalink: scpivs44_modify_storage_timeout.html 
keywords:  
summary: 'Même si les sauvegardes ont été exécutées avec succès dans le passé, elles peuvent commencer à échouer pendant le temps pendant lequel le SnapCenter Plug-in for VMware vSphere doit attendre que le système de stockage dépasse le délai d"expiration configuré.  Si cette condition se produit, vous pouvez augmenter le délai d’expiration configuré.' 
---
= Modifier le délai d'expiration de stockage configuré
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Même si les sauvegardes ont été exécutées avec succès dans le passé, elles peuvent commencer à échouer pendant le temps pendant lequel le SnapCenter Plug-in for VMware vSphere doit attendre que le système de stockage dépasse le délai d'expiration configuré.  Si cette condition se produit, vous pouvez augmenter le délai d’expiration configuré.

Vous pourriez rencontrer l'erreur `Unable to discover resources on SCV: Unable to get storage details for datastore <xxx>…`

.Étapes
. Dans le volet de navigation gauche du plug-in SCV, sélectionnez *Systèmes de stockage*.
. Sur la page Systèmes de stockage, sélectionnez le système de stockage à modifier et sélectionnez *Modifier*.
. Dans le champ Délai d’expiration, augmentez le nombre de secondes.
+

TIP: 180 secondes sont recommandées pour les grands environnements.


