---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: 'Lorsque vous attachez un disque virtuel pour des opérations de restauration de fichiers ou de dossiers invités, la machine virtuelle cible pour la connexion doit avoir des informations d"identification configurées avant la restauration.' 
---
= Configurer les informations d'identification pour les restaurations de fichiers invités de la machine virtuelle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous attachez un disque virtuel pour des opérations de restauration de fichiers ou de dossiers invités, la machine virtuelle cible pour la connexion doit avoir des informations d'identification configurées avant la restauration.

.À propos de cette tâche
Le tableau suivant répertorie les exigences d’informations d’identification pour les opérations de restauration d’invité.

|===
|  | Contrôle d'accès utilisateur activé | Contrôle d'accès utilisateur désactivé 


| Utilisateur du domaine | Un utilisateur de domaine avec « administrateur » comme nom d’utilisateur fonctionne bien.  Par exemple, «NetApp\administrateur ».  Cependant, un utilisateur de domaine avec « xyz » comme nom d’utilisateur appartenant à un groupe d’administrateurs locaux ne fonctionnera pas.  Par exemple, vous ne pouvez pas utiliser «NetApp\xyz ». | Soit un utilisateur de domaine avec « administrateur » comme nom d’utilisateur, soit un utilisateur de domaine avec « xyz » comme nom d’utilisateur appartenant à un groupe d’administrateurs locaux, fonctionne correctement.  Par exemple, «NetApp\administrateur » ou «NetApp\xyz ». 


| Utilisateur du groupe de travail | Un utilisateur local avec « administrateur » comme nom d’utilisateur fonctionne bien.  Cependant, un utilisateur local avec « xyz » comme nom d’utilisateur appartenant à un groupe d’administrateurs locaux ne fonctionnera pas. | Soit un utilisateur local avec « administrateur » comme nom d’utilisateur, soit un utilisateur local avec « xyz » comme nom d’utilisateur appartenant à un groupe d’administrateurs locaux, fonctionne correctement.  Cependant, un utilisateur local avec « xyz » comme nom d’utilisateur qui n’appartient pas au groupe d’administrateurs locaux ne fonctionnera pas. 
|===
Dans les exemples précédents, «NetApp» est le nom de domaine factice et « xyz » est le nom d’utilisateur local factice

.Étapes
. Dans la fenêtre des raccourcis du client vSphere, sélectionnez * SnapCenter Plug-in for VMware vSphere* sous Plug-ins.
. Dans la navigation de gauche, sélectionnez *Restauration de fichiers invités*.
. Dans la section *Exécuter en tant qu'informations d'identification*, effectuez l'une des opérations suivantes :
+
|===
| Pour ce faire… | Fais ceci… 


| Utiliser les informations d'identification existantes | Sélectionnez l’une des informations d’identification configurées. 


| Ajouter de nouvelles informations d'identification  a| 
.. Sélectionnez *Ajouter*.
.. Dans la boîte de dialogue *Exécuter en tant qu'informations d'identification*, saisissez les informations d'identification.  Pour le nom d’utilisateur, vous devez saisir « Administrateur ».
.. Sélectionnez *Sélectionner une machine virtuelle*, puis sélectionnez une machine virtuelle dans la boîte de dialogue *VM proxy*.  Sélectionnez *Enregistrer* pour revenir à la boîte de dialogue *Exécuter en tant qu'informations d'identification*.  Sélectionnez la machine virtuelle qui doit être utilisée pour authentifier les informations d’identification.


|===
+
Le SnapCenter Plug-in for VMware vSphere utilise les informations d’identification sélectionnées pour se connecter à la machine virtuelle sélectionnée.

. Sélectionnez *Enregistrer*.

