---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 'Vous pouvez monter une banque de données traditionnelle à partir d’une sauvegarde si vous souhaitez accéder aux fichiers de la sauvegarde. Vous pouvez monter la sauvegarde sur le même hôte ESXi où la sauvegarde a été créée ou sur un autre hôte ESXi doté du même type de configurations de machine virtuelle et d"hôte. Vous pouvez monter un magasin de données plusieurs fois sur un hôte.' 
---
= Monter une sauvegarde
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez monter une banque de données traditionnelle à partir d’une sauvegarde si vous souhaitez accéder aux fichiers de la sauvegarde. Vous pouvez monter la sauvegarde sur le même hôte ESXi où la sauvegarde a été créée ou sur un autre hôte ESXi doté du même type de configurations de machine virtuelle et d'hôte. Vous pouvez monter un magasin de données plusieurs fois sur un hôte.

Vous ne pouvez pas monter une banque de données vVol.

.Avant de commencer
* Assurez-vous que l'hôte ESXi alternatif peut se connecter au stockage
+
Si vous souhaitez effectuer un montage sur un autre hôte ESXi, vous devez vous assurer que l'autre hôte ESXi peut se connecter au stockage et dispose des éléments suivants :

+
** Même UID et GID que ceux de l'hôte d'origine
** Même appliance virtuelle pour la version SnapCenter Plug-in for VMware vSphere que celle de l'hôte d'origine


* Lorsque vous utilisez le protocole iSCSI, assurez-vous que les initiateurs du système de stockage sont mappés à l'hôte ESXi.  Lorsque vous utilisez le protocole NVMe, ajoutez des contrôleurs pour mapper le sous-système requis à l’hôte ESXi.
* Nettoyer les LUN/espaces de noms obsolètes
+
Étant donné que l’hôte ESXi ne peut découvrir qu’un seul LUN/espace de noms unique par banque de données, l’opération échouera s’il en trouve plusieurs.  Cela peut se produire si vous démarrez une opération de montage avant la fin d'une opération de montage précédente, ou si vous clonez manuellement le LUN/espace de noms, ou si les clones ne sont pas supprimés du stockage pendant une opération de démontage.  Pour éviter la découverte de plusieurs clones, vous devez nettoyer tous les LUN/espaces de noms obsolètes sur le stockage.



.À propos de cette tâche
Une opération de montage peut échouer si le niveau de stockage du FabricPool où se trouve la banque de données n'est pas disponible.

.Étapes
. Dans la page des raccourcis du client VMware vSphere, sélectionnez *Stockage*.
. Cliquez avec le bouton droit sur une banque de données et sélectionnez * SnapCenter Plug-in for VMware vSphere* > *Monter la sauvegarde*.
. Sur la page *Monter le magasin de données*, sélectionnez une sauvegarde et un emplacement de sauvegarde (principal ou secondaire), puis sélectionnez *Terminer*.
. Facultatif : pour vérifier que la banque de données est montée, procédez comme suit :
+
.. Sélectionnez *Menu* dans la barre d’outils, puis sélectionnez *Stockage* dans la liste déroulante.
.. Le volet de navigation de gauche affiche la banque de données que vous avez montée en haut de la liste.
+
Pour empêcher la création de nouveaux snapshots lorsque vous clonez le volume, désactivez la planification ONTAP pour le volume SnapVault .  Les instantanés précédemment existants ne sont pas supprimés.




