---
sidebar: sidebar 
permalink: scpivs44_set_up_proxy_vms_for_restore_operations.html 
keywords:  
summary: 'Si vous souhaitez utiliser une machine virtuelle proxy pour attacher un disque virtuel pour les opérations de restauration de fichiers invités, vous devez configurer la machine virtuelle proxy avant de commencer l"opération de restauration.  Bien que vous puissiez configurer une machine virtuelle proxy à tout moment, il peut être plus pratique de la configurer immédiatement après la fin du déploiement du plug-in.' 
---
= Configurer des machines virtuelles proxy pour les opérations de restauration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous souhaitez utiliser une machine virtuelle proxy pour attacher un disque virtuel pour les opérations de restauration de fichiers invités, vous devez configurer la machine virtuelle proxy avant de commencer l'opération de restauration.  Bien que vous puissiez configurer une machine virtuelle proxy à tout moment, il peut être plus pratique de la configurer immédiatement après la fin du déploiement du plug-in.

.Étapes
. Dans la fenêtre des raccourcis du client vSphere, sélectionnez * SnapCenter Plug-in for VMware vSphere* sous Plug-ins.
. Dans la navigation de gauche, sélectionnez *Restauration de fichiers invités*.
. Dans la section *Exécuter en tant qu'informations d'identification*, effectuez l'une des opérations suivantes :
+
|===
| Pour ce faire… | Fais ceci… 


| Utiliser les informations d'identification existantes | Sélectionnez l’une des informations d’identification configurées. 


| Ajouter de nouvelles informations d'identification  a| 
.. Sélectionnez *Ajouter*.
.. Dans la boîte de dialogue *Exécuter en tant qu'informations d'identification*, saisissez les informations d'identification.
.. Sélectionnez *Sélectionner une machine virtuelle*, puis sélectionnez une machine virtuelle dans la boîte de dialogue *VM proxy*.  Sélectionnez *Enregistrer* pour revenir à la boîte de dialogue *Exécuter en tant qu'informations d'identification*.
.. Entrez les informations d'identification. Pour le nom d’utilisateur, vous devez saisir « Administrateur ».


|===
+
Le SnapCenter Plug-in for VMware vSphere utilise les informations d’identification sélectionnées pour se connecter à la machine virtuelle proxy sélectionnée.

+
Les informations d’identification « Exécuter en tant que » doivent correspondre à l’administrateur de domaine par défaut fourni par Windows ou à l’administrateur local intégré.  Les utilisateurs du groupe de travail peuvent utiliser le compte administrateur local intégré.

. Dans la section *Informations d’identification du proxy*, sélectionnez *Ajouter* pour ajouter une machine virtuelle à utiliser comme proxy.
. Dans la boîte de dialogue *Proxy VM*, complétez les informations, puis sélectionnez *Enregistrer*.



NOTE: Vous devez supprimer la machine virtuelle proxy de l'interface utilisateur du SnapCenter Plug-in for VMware vSphere avant de pouvoir la supprimer de l'hôte ESXi.
